package com.tedaich.mobile.asr.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tedaich.mobile.asr.model.Audio;
import com.tedaich.mobile.asr.model.AudioText;
import com.tedaich.mobile.asr.model.User;

import com.tedaich.mobile.asr.dao.AudioDao;
import com.tedaich.mobile.asr.dao.AudioTextDao;
import com.tedaich.mobile.asr.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig audioDaoConfig;
    private final DaoConfig audioTextDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AudioDao audioDao;
    private final AudioTextDao audioTextDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        audioTextDaoConfig = daoConfigMap.get(AudioTextDao.class).clone();
        audioTextDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        audioDao = new AudioDao(audioDaoConfig, this);
        audioTextDao = new AudioTextDao(audioTextDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Audio.class, audioDao);
        registerDao(AudioText.class, audioTextDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        audioDaoConfig.clearIdentityScope();
        audioTextDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

    public AudioTextDao getAudioTextDao() {
        return audioTextDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
